services:
  - type: web
    name: mafita-backend
    env: python
    region: oregon          # optional – change if you prefer another region
    plan: free              # or starter/professional, etc.

    # ---- IMPORTANT: lock the runtime ----
    pythonVersion: "3.13"   # matches pillow-12.0.0-cp313 wheel

    # ---- Simple, deterministic build ----
    buildCommand: >-
      pip install --upgrade pip &&
      pip install -r requirements.txt

    startCommand: gunicorn backend.wsgi:application

    # ---- Environment variables ----
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: mafitapay.com,api.mafitapay.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://mafitapay.com,https://api.mafitapay.com
      - key: PYTHONUNBUFFERED
        value: "1"          # nice for logs

    # ---- Optional: health-check (recommended) ----
    healthCheckPath: /healthz/
