# Generated by Django 5.1.7 on 2025-05-26 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_buyoffer_sellorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyOffer',
            new_name='Deposit_P2P_Offer',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='DepositOrder',
        ),
        migrations.RenameModel(
            old_name='SellOffer',
            new_name='Withdraw_P2P_Offer',
        ),
        migrations.RenameModel(
            old_name='SellOrder',
            new_name='WithdrawOrder',
        ),
        migrations.RenameField(
            model_name='deposit_p2p_offer',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='withdraw_p2p_offer',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
