# Generated by Django 5.1.7 on 2025-05-26 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_rename_buyoffer_deposit_p2p_offer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositorder',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='depositorder',
            name='sell_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2p.deposit_p2p_offer'),
        ),
        migrations.AlterField(
            model_name='withdraworder',
            name='buyer_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2p.withdraw_p2p_offer'),
        ),
    ]
