# Generated by Django 5.1.7 on 2025-05-26 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0005_alter_depositorder_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositorder',
            name='sell_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='p2p.deposit_p2p_offer'),
        ),
    ]
