# Generated by Django 5.1.7 on 2025-05-14 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSellOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('usdt', 'USDT'), ('bnb', 'BNB')], max_length=10)),
                ('source', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('mexc', 'MEXC'), ('gateio', 'Gate.io'), ('bitget', 'Bitget'), ('wallet', 'External Wallet')], max_length=20)),
                ('amount_asset', models.DecimalField(decimal_places=8, max_digits=18)),
                ('rate_ngn', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount_ngn', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
