# Generated by Django 5.1.7 on 2025-05-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('binance', 'Binance'), ('bybit', 'Bybit'), ('mexc', 'MEXC'), ('gateio', 'Gate.io'), ('bitget', 'Bitget'), ('wallet', 'External Wallet')], max_length=20, unique=True)),
                ('receive_qr', models.ImageField(upload_to='exchange_qrcodes/')),
                ('contact_info', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
