# Generated by Django 5.1.7 on 2025-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_paymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeinfo',
            name='receive_qr',
            field=models.ImageField(blank=True, null=True, upload_to='exchange_qrcodes/'),
        ),
    ]
