# Generated by Django 5.1.7 on 2025-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
