# Generated by Django 5.1.7 on 2025-04-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/bnb-bnb-logo.png', null=True, upload_to='profile_images/'),
        ),
    ]
