# Generated by Django 5.1.7 on 2025-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='logo',
            field=models.ImageField(default='default_logo.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='cryptopurchase',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptopurchase',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
