# Generated by Django 5.1.7 on 2025-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0002_crypto_logo_cryptopurchase_settled_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptopurchase',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cryptopurchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cryptopurchase',
            name='settled_at',
        ),
        migrations.RemoveField(
            model_name='cryptopurchase',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='cryptopurchase',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptopurchase',
            name='input_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptopurchase',
            name='input_currency',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cryptopurchase',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptopurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cryptopurchase',
            name='wallet_address',
            field=models.CharField(max_length=255),
        ),
    ]
