# Generated by Django 5.1.7 on 2025-03-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0003_rename_timestamp_cryptopurchase_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(default='USDT/NGN', max_length=20, unique=True)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
