# Generated by Django 5.1.7 on 2025-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0004_exchangeratemargin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='available',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='price_rate',
        ),
        migrations.AddField(
            model_name='crypto',
            name='coingecko_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
