# Generated by Django 5.1.7 on 2025-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0005_remove_crypto_available_remove_crypto_price_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopurchase',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
