# Generated by Django 5.1.7 on 2025-03-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0006_cryptopurchase_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='network',
            field=models.CharField(default='Ethereum', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='crypto',
            unique_together={('coingecko_id', 'network')},
        ),
    ]
