# Generated by Django 5.1.7 on 2025-03-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0008_alter_crypto_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='coingecko_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
