# Generated by Django 5.1.7 on 2025-03-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0009_alter_crypto_coingecko_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
