# Generated by Django 5.1.7 on 2025-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0011_alter_crypto_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='network',
            field=models.CharField(choices=[('ETH', 'Ethereum'), ('BNB', 'Binance Smart Chain'), ('ARB', 'Arbitrum'), ('BASE', 'Base'), ('OP', 'Optimism'), ('SOL', 'Solana')], max_length=50),
        ),
    ]
