# Generated by Django 5.1.7 on 2025-04-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0012_alter_crypto_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='network',
            field=models.CharField(choices=[('ETH', 'Ethereum'), ('BNB', 'Binance Smart Chain'), ('ARB', 'Arbitrum'), ('BASE', 'Base'), ('OP', 'Optimism'), ('SOL', 'Solana'), ('TON', 'The-Open-Network'), ('SUI', 'Sui-Network'), ('NEAR', 'Near-Protocol'), ('POL', 'Polygon'), ('AVAX', 'Avalanche'), ('TRON', 'Tron'), ('XRP', 'XRP Ledger'), ('ADA', 'Cardano'), ('DOT', 'Polkadot'), ('LTC', 'Litecoin'), ('DOGE', 'Dogecoin'), ('SHIB', 'Shiba Inu'), ('MATIC', 'Polygon-MATIC'), ('FIL', 'Filecoin')], max_length=50),
        ),
    ]
