# Generated by Django 5.1.7 on 2025-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfee', '0013_alter_crypto_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='logo',
            field=models.ImageField(default='default_crypto_logo.png', upload_to='images/'),
        ),
    ]
